version: "3.1"

services:
  db:
    image: mysql:latest
    container_name: mysql_studyroombackend
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_DOCKER_HOST}
    ports:
      - "3307:3306"
#     volumes:
#       - dbdata:/var/lib/mysql

# volumes:
#   dbdata:
